projects:
  kitefrontend:
    schemaPath: amplify/backend/api/kitefrontend/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: ap-south-1
        apiId: null
        maxDepth: 2
