/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_appsync_graphqlEndpoint": "https://a2temih7hfhk5haauiiithf4ge.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-c7jfj3hxujdwbhfcqobtitvfoe",
    "aws_cloud_logic_custom": [
        {
            "name": "kiterestapi",
            "endpoint": "https://o8zphk0g27.execute-api.ap-south-1.amazonaws.com/prod",
            "region": "ap-south-1"
        }
    ],
    "aws_cognito_identity_pool_id": "ap-south-1:353961ec-18bf-49c9-82f8-3cc0a46ee4ed",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_wmFFMNf1O",
    "aws_user_pools_web_client_id": "562l8pu3o5ujbvrt4doactpm1b",
    "oauth": {
        "domain": "fx4iju9c5gwz-prod.auth.ap-south-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://www.kitefy.in/",
        "redirectSignOut": "https://www.kitefy.in/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
