export { default as HeroSection } from './hero-section'
export { default as FeaturedSection } from './featured_section'
export { default as PackagesSection } from './trips/packages-section'
export { default as DiscoverTheWorld } from './discover_world'
export { default as NextDestinationForm } from './nextDestinationForm'
export { default as Activities } from './trips/activities_section'